grafana:
  server:
    domain: gsking.co.uk
    root_url: "https://grafana.gsking.co.uk"
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
    hosts:
      - "grafana.gsking.co.uk"
