apiVersion: v2
name: argocd
description: Community maintained Argo helm chart

type: application

version: 0.1.0

appVersion: 0.1.0

dependencies:
  - name: argo-cd
    version: 5.33.3
    repository: https://argoproj.github.io/argo-helm
    alias: argocd